apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: scw-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    scaleway:
      region: nl-ams
      projectId: 81fba592-e69f-4d95-94bd-b362fcb77300
      accessKey:
        secretRef:
          name: scwsm-access
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-access
          key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-sentry-dsn
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: scw-secret-store
    target:
        name: my-sentry-dsn
        creationPolicy: Owner
    data:
      - secretKey: dsn
        remoteRef:
          key: id:2320501b-1ad3-4516-9088-50ee3c57ae3e
          version: latest_enabled

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-slack-webhook-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: scw-secret-store
    target:
        name: slack-webhook-devops
        creationPolicy: Owner
    data:
      - secretKey: webhook
        remoteRef:
          key: id:b17b0582-56f0-475e-93fc-1eb5173c1fa7
          version: latest_enabled

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-argocd-login
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: scw-secret-store
    target:
        name: argocd-login
        creationPolicy: Owner
    data:
      - secretKey: hest
        remoteRef:
          key: id:a68c441e-b061-4f3e-8aac-f8ee0e7d6599
          version: latest_enabled
