apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: alert-sentry
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: alert-sentry
  arguments:
    parameters:
    - name: message
  templates:
  - name: alert-sentry
    inputs:
      parameters:
      - name: message
    outputs:
      parameters:
      - name: event-id
        valueFrom:
          path: /tmp/event-id
      - name: event-url
        valueFrom:
          path: /tmp/event-url
    script:
      image: prakahe/argo-cluster-control:latest
      command: [sh]
      source: |
        export SENTRY_DSN="https://add568bc79479f8633f796ac375e2a52@o4508840730689536.ingest.de.sentry.io/4508840737833040"

        org_slug="myorganization-ti"
        event_id=$(sentry-cli send-event --raw -m '{{workflow.name}} : {{inputs.parameters.message}}' | grep -oP '(?<=Event id: )[\w-]+')

        echo $event_id > /tmp/event-id
        echo https://sentry.io/organizations/$org_slug/issues/?query=$event_id > /tmp/event-url
