apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: alert
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: alert-error
  arguments:
    parameters:
    - name: message
  templates:
  - name: alert-error
    inputs:
      parameters:
      - name: message
    steps:
    - - name: alert-sentry
        templateRef:
          name: alert-sentry
          template: alert-sentry
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
    - - name: alert-slack-error
        templateRef:
          name: alert-slack
          template: alert-slack-error
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
      - name: alert-slack-sentry-url
        templateRef:
          name: alert-slack
          template: alert-slack-error-sub
        arguments:
          parameters:
          - name: message
            value: "Sentry event: {{steps.alert-sentry.outputs.parameters.event-url}}"
