apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: alert-slack
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: alert-slack
  arguments:
    parameters:
    - name: message
  templates:
  - name: alert-slack
    inputs:
      parameters:
      - name: message
        value: "asdasdasdasd"
    steps:
    - - name: send-slack-message
        template: send-slack-message
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"

  - name: alert-slack-success
    inputs:
      parameters:
      - name: message
        value: "asdasdasdasdsuccess"
    steps:
    - - name: send-slack-message
        template: send-slack-message
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
          - name: emoji
            value: ":heavy_check_mark:"

  - name: alert-slack-success-loud
    inputs:
      parameters:
      - name: message
        value: "asdasdasdasdsuccessloud"
    steps:
    - - name: send-slack-message
        template: send-slack-message
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
          - name: emoji
            value: ":white_check_mark:"

  - name: alert-slack-warning
    inputs:
      parameters:
      - name: message
        value: "asdasdasdasdwarning"
    steps:
    - - name: send-slack-message
        template: send-slack-message
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
          - name: emoji
            value: ":warning:"

  - name: alert-slack-error
    inputs:
      parameters:
      - name: message
        value: "asdasdasdasderror"
    steps:
    - - name: send-slack-message
        template: send-slack-message
        arguments:
          parameters:
          - name: message
            value: "{{inputs.parameters.message}}"
          - name: emoji
            value: ":x:"

  - name: send-slack-message
    inputs:
      parameters:
      - name: message
      - name: emoji
        value: ":white_small_square:"
    script:
      image: appropriate/curl:latest
      command: [sh, -c]
      source: |
        echo "{{inputs.parameters.message}}"
        cred="T08EH7TLVBJ/B08EHMA0H4N/F3zpHs4aBsaXqYbtJYnODWn9"
        curl -X POST -H 'Content-type: application/json' --data '{"text":"{{inputs.parameters.emoji}} -> {{workflow.name}} -> {{inputs.parameters.message}}"}' https://hooks.slack.com/services/$cred
