apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: alert-sentry
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: alert-sentry
  arguments:
    parameters:
    - name: message
  templates:
  - name: alert-sentry
    inputs:
      parameters:
      - name: message
    outputs:
      parameters:
      - name: event-id
        valueFrom:
          path: /tmp/event-id
      - name: event-url
        valueFrom:
          path: /tmp/event-url
    script:
      image: prakahe/argo-cluster-control:3
      command: [sh]
      env:
      - name: SENTRY_WORKFLOWS_DSN
        valueFrom:
          secretKeyRef:
            name: external
            key: SENTRY_WORKFLOWS_DSN
      source: |
        export SENTRY_DSN=$SENTRY_WORKFLOWS_DSN

        org_slug="myorganization-ti"
        event_id=$(sentry-cli send-event --raw -m '{{workflow.mainEntrypoint}} : {{inputs.parameters.message}}' -e workflow-name:{{workflow.name}} -e workflow-status:{{workflow.status}} | grep -oP '(?<=Event id: )[\w-]+')

        echo $event_id > /tmp/event-id
        echo https://sentry.io/organizations/$org_slug/issues/?query=$event_id > /tmp/event-url
