apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-list-of-apps
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: deploy-list-of-apps
  onExit: exit-handler
  arguments:
    parameters:
    - name: app-names
      value: |
        [
          "guestbook",
          "hello-world-api",
          "fastapi-sample-app",
          "hello-world-api-1",
          "hello-world-api-2",
          "hello-world-api-3",
          "hello-world-api-4",
          "hello-world-api-5",
          "hello-world-api-6",
          "workflows",
          "workflows-demos"
        ]
    - name: monitor-timeout-seconds
      value: 5
  parallelism: 1
  templates:
  - name: deploy-list-of-apps
    failFast: true
    inputs:
      parameters:
      - name: app-names
      - name: monitor-timeout-seconds
    steps:
    - - name: alert-deployments-started
        templateRef:
          name: alert-slack
          template: alert-slack
        arguments:
          parameters:
          - name: message
            value: "Deployments started..."
    - - name: deploy-app
        templateRef:
          name: deploy-app
          template: deploy-app
        arguments:
          parameters:
          - name: app-name
            value: "{{item}}"
          - name: monitor-timeout-seconds
            value: "{{inputs.parameters.monitor-timeout-seconds}}"
        withParam: "{{inputs.parameters.app-names}}"

  # exit-handler is ONLY run if the 'deploy-list-of-apps' workflowTemplate is submitted. 
  # It is not run if the 'deploy-list-of-apps' template is referenced by another workflow.
  - name: exit-handler
    steps:
    - - name: handle-success
        when: "{{workflow.status}} == Succeeded"
        template: handle-success
      - name: handle-failed
        when: "{{workflow.status}} != Succeeded"
        template: handle-failed

  - name: handle-success
    steps:
    - - name: alert-slack-1
        templateRef:
          name: alert-slack
          template: alert-slack-success-loud
        arguments:
          parameters:
          - name: message
            value: "Deployments completed without errors."

  - name: handle-failed
    steps:
    - - name: alert-slack
        templateRef:
          name: alert-slack
          template: alert-slack-error
        arguments:
          parameters:
          - name: message
            value: "Deployment failed. Workflow {{workflow.mainEntrypoint}} finished with status `{{workflow.status}}`"
      - name: alert-sentry
        templateRef:
          name: alert-sentry
          template: alert-sentry
        arguments:
          parameters:
          - name: message
            value: "Deployment failed. Workflow {{workflow.mainEntrypoint}} finished with status `{{workflow.status}}`"
  
    # steps:
    # - - name: alert-slack-on-success
    #     when: "{{workflow.status}} == Succeeded"
    #     templateRef:
    #       name: alert-slack
    #       template: alert-slack-success
    #     arguments:
    #       parameters:
    #       - name: message
    #         value: "Deployment workflow {{workflow.mainEntrypoint}} finished with status {{workflow.status}}"
    #   - name: alert-slack-on-failed
    #     when: "{{workflow.status}} != Succeeded"
    #     templateRef:
    #       name: alert-slack
    #       template: alert-slack-error
    #     arguments:
    #       parameters:
    #       - name: message
    #         value: "Deployment workflow {{workflow.mainEntrypoint}} finished with status {{workflow.status}}"
    #   - name: alert-sentry-on-failed
    #     when: "{{workflow.status}} != Succeeded"
    #     templateRef:
    #       name: alert-sentry
    #       template: alert-sentry
    #     arguments:
    #       parameters:
    #       - name: message
    #         value: "Deployment workflow {{workflow.mainEntrypoint}} failed"
