apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-app
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: deploy-app
  arguments:
    parameters:
    - name: app-name
      value: "guestbook"
    - name: monitor-timeout-seconds
      value: 120
  templates:
  - name: deploy-app
    inputs:
      parameters:
      - name: app-name
      - name: monitor-timeout-seconds
    steps:
    - - name: sync-app
        template: sync-app
        arguments:
          parameters:
          - name: app-name
            value: "{{inputs.parameters.app-name}}"
    - - name: monitor-deployment
        template: monitor-deployment
        arguments:
          parameters:
          - name: app-name
            value: "{{inputs.parameters.app-name}}"
          - name: monitor-timeout-seconds
            value: "{{inputs.parameters.monitor-timeout-seconds}}"

  - name: sync-app
    inputs:
      parameters:
      - name: app-name
    script:
      image: argoproj/argocd:latest
      command: [sh]
      source: |
        echo "Logging in to Argo CD..."
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass
        echo "Syncing application {{inputs.parameters.app-name}}..."
        argocd app sync {{inputs.parameters.app-name}}

  - name: monitor-deployment
    script:
      image: prakahe/argo-cluster-control:latest
      command: [sh]
      source: |
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass
        export SENTRY_DSN="https://add568bc79479f8633f796ac375e2a52@o4508840730689536.ingest.de.sentry.io/4508840737833040"

        i=1
        while [ $i -le {{workflow.parameters.monitor-timeout-seconds}} ]
        do
          status=$(argocd app get {{workflow.parameters.app-name}} -o json | jq -r .status.health.status)
          echo $status
          echo "Remaining seconds: $(( {{workflow.parameters.monitor-timeout-seconds}} - i ))"

          if [ "$status" = "Degraded" ]; then
            echo "{{workflow.parameters.app-name}} application is Degraded"
            sentry-cli send-event -m "Deployment of application \'{{workflow.parameters.app-name}}\' failed." -m "Application is Degraded."
            exit 1
          fi

          if [ "$status" = "Healthy asdasdasdasd" ]; then
            echo "{{workflow.parameters.app-name}} application is Healthy"
            exit 0
          fi

          i=$((i + 1))
          sleep 1
        done

        echo "Timed out after {{workflow.parameters.monitor-timeout-seconds}} seconds"
        sentry-cli send-event -m "Deployment of application \'{{workflow.parameters.app-name}}\' failed." -m "Monitor timed out after {{workflow.parameters.monitor-timeout-seconds}} seconds."
        exit 1
