apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-app
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: deploy-app
  onExit: exit-handler
  arguments:
    parameters:
    - name: app-name
      value: "fastapi-sample-app"
    - name: monitor-timeout-seconds
      value: 120
  templates:
  - name: deploy-app
    inputs:
      parameters:
      - name: app-name
      - name: monitor-timeout-seconds
    steps:
    - - name: sync-app
        template: sync-app
        arguments:
          parameters:
          - name: app-name
            value: "{{inputs.parameters.app-name}}"
    - - name: monitor-deployment
        template: monitor-deployment
        arguments:
          parameters:
          - name: app-name
            value: "{{inputs.parameters.app-name}}"
          - name: monitor-timeout-seconds
            value: "{{inputs.parameters.monitor-timeout-seconds}}"
    outputs:
      parameters:
      - name: deployment-status
        valueFrom:
          parameter: "{{steps.monitor-deployment.outputs.parameters.deployment-status}}"


  - name: sync-app
    inputs:
      parameters:
      - name: app-name
    script:
      image: argoproj/argocd:latest
      command: [sh]
      source: |
        echo "Logging in to Argo CD..."
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass
        echo "Syncing application {{inputs.parameters.app-name}}..."
        argocd app sync {{inputs.parameters.app-name}}

  - name: monitor-deployment
    inputs:
      parameters:
      - name: app-name
      - name: monitor-timeout-seconds
    outputs:
      parameters:
      - name: deployment-status
        valueFrom:
          path: /tmp/deployment-status
    script:
      image: prakahe/argo-cluster-control:latest
      command: [sh]
      source: |
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass

        i=1
        while [ $i -le {{inputs.parameters.monitor-timeout-seconds}} ]
        do
          status=$(argocd app get {{inputs.parameters.app-name}} -o json | jq -r .status.health.status)
          echo $status
          echo "Remaining seconds: $(( {{inputs.parameters.monitor-timeout-seconds}} - i ))"

          if [ "$status" = "Degraded" ]; then
            echo "{{inputs.parameters.app-name}} application is Degraded"
            echo "Degraded" > /tmp/deployment-status
            exit 1
          fi

          if [ "$status" = "Healthy" ]; then
            echo "{{inputs.parameters.app-name}} application is Healthy"
            echo "Healthy" > /tmp/deployment-status
            exit 0
          fi

          i=$((i + 1))
          sleep 1
        done

        echo "Timed out after {{inputs.parameters.monitor-timeout-seconds}} seconds"
        echo "Timeout" > /tmp/deployment-status
        exit 1

  - name: exit-handler
    inputs:
      parameters:
      - name: app-name
        value: "fastapi-sample-app-hest"
    script:
      image: prakahe/argo-cluster-control:latest
      command: [sh]
      source: |
        echo {{inputs.parameters.app-name}}
        echo {{workflow.outputs.parameters.deployment-status}}
    # steps:
    # - - name: alert-sentry-degraded
    #     when: "{{workflow.outputs.parameters.deployment-status}} == Degraded"
    #     templateRef:
    #       name: alert-sentry
    #       template: alert-sentry
    #     arguments:
    #       parameters:
    #       - name: message
    #         value: "Deployment of application '{{inputs.parameters.app-name}}' failed. Application is Degraded."
      # - name: alert-sentry-timeout
      #   when: "{{inputs.parameters.deployment-status}} == Timeout"
      #   templateRef:
      #     name: alert-sentry
      #     template: alert-sentry
      #   arguments:
      #     parameters:
      #     - name: message
      #       value: "Deployment of application '{{inputs.parameters.app-name}}' failed. Monitor timed out after {{inputs.parameters.monitor-timeout-seconds}} seconds."
      # - name: alert-sentry-success
      #   when: "{{inputs.parameters.deployment-status}} == Healthy"
      #   templateRef:
      #     name: alert-sentry
      #     template: alert-sentry
      #   arguments:
      #     parameters:
      #     - name: message
      #       value: "Deployment of application '{{inputs.parameters.app-name}}' succeeded. Application is Healthy."
