apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-list-of-apps
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: deploy-list-of-apps
  onExit: exit-handler
  arguments:
    parameters:
    - name: app-names
      value: |
        [
          "guestbook",
          "fastapi-sample-app",
          "hello-world-api",
          "hello-world-api-1",
          "hello-world-api-2",
          "hello-world-api-3",
          "hello-world-api-4",
          "hello-world-api-5",
          "hello-world-api-6",
          "workflows",
          "workflows-demos"
        ]
    - name: monitor-timeout-seconds
      value: 5
  parallelism: 1
  templates:
  - name: deploy-list-of-apps
    failFast: true
    inputs:
      parameters:
      - name: app-names
      - name: monitor-timeout-seconds
    steps:
    - - name: deploy-app
        templateRef:
          name: deploy-app
          template: deploy-app
        arguments:
          parameters:
          - name: app-name
            value: "{{item}}"
          - name: monitor-timeout-seconds
            value: "{{inputs.parameters.monitor-timeout-seconds}}"
        withParam: "{{inputs.parameters.app-names}}"

  - name: exit-handler
    # when: "{{workflow.status}} != Succeeded"
    templateRef:
      name: alert-sentry
      template: alert-sentry
    arguments:
      parameters:
      - name: message
        value: "This workflow failed! Hest!"
