apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-app
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: deploy-app
  arguments:
    parameters:
    - name: app-name
      value: "guestbook"
    - name: monitor-timeout-seconds
      value: 120
  templates:
  - name: deploy-app
    steps:
    - - name: sync-app
        template: sync-app
    - - name: monitor-deployment
        template: monitor-deployment

  - name: sync-app
    script:
      image: argoproj/argocd:latest
      command: [sh]
      source: |
        echo "Logging in to Argo CD..."
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass
        echo "Syncing application {{workflow.parameters.app-name}}..."
        argocd app sync {{workflow.parameters.app-name}}

  - name: monitor-deployment
    script:
      image: prakahe/argo-cluster-control:latest
      command: [sh]
      source: |
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass
        export SENTRY_DSN="https://310e4e49a5bdc439f87f68f566afaa02@o4508840367882240.ingest.de.sentry.io/4508840377253968"

        x=1
        while [ $x -le {{workflow.parameters.monitor-timeout-seconds}} ]
        do
          status=$(argocd app get {{workflow.parameters.app-name}} -o json | jq -r .status.health.status)
          echo $status
          echo "Remaining seconds: $(( {{workflow.parameters.monitor-timeout-seconds}} - x ))"

          if [ "$status" = "Degraded" ]; then
            echo "{{workflow.parameters.app-name}} application is Degraded"
            sentry-cli send-event -m "Deployment of application \"{{workflow.parameters.app-name}}\" failed." -m "Application is Degraded."
            exit 1
          fi

          if [ "$status" = "Healthy" ]; then
            echo "{{workflow.parameters.app-name}} application is Healthy"
            exit 0
          fi
          
          (($x++))
          sleep 1
        done

        echo "Timed out after {{workflow.parameters.monitor-timeout-seconds}} seconds"
        sentry-cli send-event -m "Deployment of application \"{{workflow.parameters.app-name}}\" failed." -m "Monitor timed out after {{workflow.parameters.monitor-timeout-seconds}} seconds."
        exit 1
