apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
  namespace: argo-workflows-demos
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-semaphores
  namespace: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  "1": "1"
  "2": "2"
  "3": "3"
  "4": "4"
  "6": "6"
  "8": "8"
  "10": "10"
  "12": "12"
  "16": "16"
