apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-step
  annotations:
    workflows.argoproj.io/description: This is a basic hello world workflow that prints hello.
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: hello
  arguments:
    parameters:
    - name: string-list
      value: |
        [
          "1 Hello 1!!!",
          "2 Hej! :D",
          "3 Heeeeeststst",
        ]
  templates:
  - name: hello
    steps:
    - - name: hello
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{inputs.parameters.os-list}}"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: busybox
      command: [echo]
      args: ["{{inputs.parameters.message}}"]
