apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: z-hello-step
  annotations:
    workflows.argoproj.io/description: This is a basic hello world workflow that prints hello.
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: hello

  templates:
  - name: hello
    steps:
    - - name: hello
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "hello hest!!! Wowow!"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: busybox
      command: [echo]
      args: ["{{inputs.parameters.message}}"]
