apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-app
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: deploy-app
  arguments:
    parameters:
    - name: app-name
      value: "guestbook"
    - name: monitor-timeout-seconds
      value: 120
  templates:
  - name: deploy-app
    steps:
    - - name: sync-app
        template: sync-app
    - - name: monitor-rollout
        template: monitor-rollout

  - name: sync-app
    script:
      image: argoproj/argocd:latest
      command: [sh]
      source: |
        echo "Logging in to Argo CD..."
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass
        echo "Syncing application {{workflow.parameters.app-name}}..."
        argocd app sync {{workflow.parameters.app-name}}

  - name: monitor-rollout
    script:
      image: prakahe/argo-cluster-control:latest
      command: [sh]
      source: |
        argocd login argocd-server.argocd.svc.cluster.local --insecure --username admin --password adminpass

        x=1
        while [ $x -le {{workflow.parameters.monitor-timeout-seconds}} ]
        do
          status=$(argocd app get {{workflow.parameters.app-name}} -o json | jq -r .status.health.status)
          echo $status

          if [ "$status" = "Degraded" ]; then
            echo "{{workflow.parameters.app-name}} application is Degraded"
            exit 1
          fi

          if [ "$status" = "Healthy" ]; then
            echo "{{workflow.parameters.app-name}} application is Healthy"
            exit 0
          fi
          
          x=$(( $x + 1 ))
          sleep 1
        done

        echo "Timed out after {{workflow.parameters.monitor-timeout-seconds}} seconds"
        exit 1
