apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fail-workflow
  annotations:
    workflows.argoproj.io/maintainer: andreas
spec:
  entrypoint: fail-workflow
  templates:
    - name: fail-workflow
      script:
        image: rg.nl-ams.scw.cloud/b2c-prak/argo-workflow-tools:2025.03.04-16
        command:
          - sh
        source: |
          exit 1
