apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/namespace.yaml
- base/rollout.yaml
# - base/deployment.yaml
- base/service.yaml
- base/ingress.yaml
- canary/canary-service.yaml
