apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/guestbook-namespace.yaml
- base/guestbook-rollout.yaml
- canary/canary-service.yaml
- canary/canary-ingress.yaml
- canary/canary-preview-service.yaml
- canary/canary-preview-ingress.yaml
# - canary/ingress.yaml
