apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - name: http
          containerPort: 80
        env:
        - name: MESSAGE
          value: "Hest!!"
  strategy:
    canary:
      stableService: canary-demo
      canaryService: canary-demo-preview
      trafficRouting:
        nginx:
          stableIngress: canary-demo
      steps:
      - setWeight: 20
      - pause: {duration: "30s"}
      - setWeight: 60
      - pause: {duration: "30s"}
