apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role-demo
  namespace: argo-workflows-demos
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding-demo
  namespace: argo-workflows-demos
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-role-demo
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows-demos
