apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      labels:
        app: hello-world-api
    spec:
      containers:
      - image: nmatsui/hello-world-api:0.1.1
        name: hello-world-api
        ports:
        - containerPort: 3000
        env:
        - name: MESSAGE
          value: "Hello another Hest!"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-api
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hello-world-api
  type: LoadBalancer
