name: Release-Workflow-Tools

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: self-hosted
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create git tag
        id: tag
        uses: Digital-Udvikling/actions-calver@v0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: self-hosted
    needs: [ tag ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ORG_PRIVATE_KEY }}
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - name: Login to scaleway registry
        uses: docker/login-action@v3
        with:
          registry: rg.nl-ams.scw.cloud/aob2c-main
          username: ${{ secrets.SCALEWAY_PRODUCTION_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.SCALEWAY_PRODUCTION_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          build-args: |
            release=${{ needs.tag.outputs.tag }}
          context: .
          push: true
          tags: |
            rg.nl-ams.scw.cloud/aob2c-main/reviews:${{ needs.tag.outputs.tag }}
            rg.nl-ams.scw.cloud/aob2c-main/reviews:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ssh: default
  bump-gitops:
    runs-on: self-hosted
    needs: [tag, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump gitops version
        uses: fjogeleit/yaml-update-action@v0.13.2
        with:
          branch: master
          message: "ci: aob2c-main/reviews updated to ${{ needs.tag.outputs.tag }}"
          token: ${{ secrets.ORG_PAT }}
          changes: |
            {
              ".ao/k8s/deployment.yaml": {
                "spec.template.spec.containers.0.image": "rg.nl-ams.scw.cloud/aob2c-main/reviews:${{ needs.tag.outputs.tag }}"
              },
              ".ao/k8s/cronjob-cleanup.yaml": {
                "spec.jobTemplate.spec.template.spec.containers.0.image": "rg.nl-ams.scw.cloud/aob2c-main/reviews:${{ needs.tag.outputs.tag }}"
              },
              ".ao/k8s/cronjob-ai-classification.yaml": {
                "spec.jobTemplate.spec.template.spec.containers.0.image": "rg.nl-ams.scw.cloud/aob2c-main/reviews:${{ needs.tag.outputs.tag }}"
              }
            }
  notify:
    runs-on: self-hosted
    needs: [ tag, build, bump-gitops ]
    steps:
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ needs.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: "{\"version\":\"${{ needs.tag.outputs.tag }}\", \"app\":\"${{ github.event.repository.name }}\", \"url\":\"${{ steps.release.outputs.url }}\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
