apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-sample-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /fas(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-sample-app
            port:
              name: http
