apiVersion: v1
kind: Service
metadata:
  name: fastapi-sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fastapi-sample-app
  type: LoadBalancer
