apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    app: argo-server
  ports:
    - port: 80
      targetPort: 2746
      protocol: TCP
  type: LoadBalancer
