apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-sample-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fastapi-sample-app
  template:
    metadata:
      labels:
        app: fastapi-sample-app
    spec:
      containers:
      - image: prakahe/fastapi-sample-app:6fWhPipTBVxN8
        imagePullPolicy: Always
        name: fastapi-sample-app
        ports:
        - containerPort: 8000
        env:
        - name: MESSAGE
          value: "So many horse hest horses from Kubernetes!!!!!! :D"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "fastapi_db"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        livenessProbe:
          httpGet:
            path: /h
            port: 8000
          initialDelaySeconds: 6
          periodSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: fastapi-sample-app
  type: LoadBalancer
