apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sample-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fastapi-sample-app
  template:
    metadata:
      labels:
        app: fastapi-sample-app
    spec:
      containers:
      - image: prakahe/fastapi-sample-app:cKP4hEmRYn9FA
        imagePullPolicy: Always
        name: fastapi-sample-app
        ports:
        - containerPort: 8000
        env:
        - name: MESSAGE
          value: "Horse hest horses from Kubernetes!"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "fastapi_db"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-sample-app
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: fastapi-sample-app
  type: LoadBalancer
