apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-sample-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fastapi-sample-app
  template:
    metadata:
      labels:
        app: fastapi-sample-app
    spec:
      containers:
      - image: prakahe/fastapi-sample-app:ToxROUKSX3si3
        imagePullPolicy: Always
        name: fastapi-sample-app
        ports:
        - containerPort: 8000
        env:
        - name: MESSAGE
          value: "Hello from Kubernetes!!!!"
        - name: CRASH_ON_START
          value: "false"
        - name: POSTGRES_HOST
          value: "postgres-service-aaaaaaaaaaaaaaasdasdasdasd"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "fastapi_db"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        restartPolicy: Never
        livenessProbe:
          httpGet:
            path: /h
            port: 8000
          initialDelaySeconds: 6
          periodSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /h
            port: 8000
          periodSeconds: 3
          failureThreshold: 6
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k8s.scaleway.com/array
                operator: In
                values:
                - PROD
      tolerations:
      - effect: NoSchedule
        key: k8s.scaleway.com/target-array
        operator: Equal
        value: PROD

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: fastapi-sample-app
  type: LoadBalancer
