apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - app/deployment.yaml
# - app/ingress.yaml
- app/namespace.yaml
- app/rollout.yaml
- app/service.yaml
- canary/canary-service.yaml
- db/db.yaml
