apiVersion: v1
kind: Namespace
metadata:
  name: guestbook2

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PrakAnHe/app-of-apps-demo.git'
    targetRevision: HEAD
    path: '.ao/k8s/guestbook'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook2
