apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: default
spec:
  provider:
    scaleway:
      region: AMS
      projectId: 81fba592-e69f-4d95-94bd-b362fcb77300
      accessKey:
        secretRef:
          name: scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-secret
          key: secret-access-key

---
