apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-secret-store
  namespace: default
spec:
  provider:
    scaleway:
      region: nl-ams
      projectId: 81fba592-e69f-4d95-94bd-b362fcb77300
      accessKey:
        secretRef:
          name: scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-secret
          key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: my-external-secret
    namespace: default
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: my-secret-store
    target:
        name: my-sentry-dsn
        creationPolicy: Owner
    data:
      - secretKey: password  # key in the kubernetes secret
        remoteRef:
          key: id:2320501b-1ad3-4516-9088-50ee3c57ae3e
          version: latest_enabled
