apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: argo
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PrakAnHe/app-of-apps-demo.git'
    targetRevision: HEAD
    path: '.ao/workflows'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
