apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  sources:
    - repoURL: 'https://github.com/PrakAnHe/app-of-apps-demo.git'
      path: '.ao/argo-workflows/auxiliaries'
      targetRevision: HEAD
    - repoURL: 'https://github.com/PrakAnHe/app-of-apps-demo.git'
      path: '.ao/argo-workflows/templates'
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
