apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows-demos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PrakAnHe/app-of-apps-demo.git'
    targetRevision: HEAD
    path: '.ao/workflows/demos'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
